### ISSUE TITLE
fix first run - notes

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/haproxy#1]
```
mkdir haproxy/certs

haproxy_1           | [ALERT] 103/174458 (5) : Proxy 'https-in': no SSL certificate specified for bind '*:443' at [/etc/haproxy/haproxy.cfg:25] (use 'crt').
```

**Comment by pierreozoux** [comment]
race condition:

HAProxy can't start because it doesn't have certs.
Letsencrypt doesn't want to start because no HAProxy.

2 ways of solving:
- self sign a cert in certs folder
- bind 80 and  443 to nginx

**Comment by unteem** [comment]
option chosen: 
self signed certificate in ./haproxy/certs/default.pem
