### ISSUE TITLE
LE cert requires haproxy restart when new domain is added

### ISSUE THREAD

**Issue by edrex** [indiehosters/haproxy#7]
For example:

```
core@libre /$ sudo libre provision -a github.com/indiehosters/nextcloud -u nextcloud.pdxhub.org -s
```

At this point the server has a self-signed cert

```
subject=/C=FR/ST=Some-State/L=flers/O=Internet Widgits Pty Ltd/OU=Timothee/CN=Timothee/emailAddress=timothee@unteem.org
issuer=/C=FR/ST=Some-State/L=flers/O=Internet Widgits Pty Ltd/OU=Timothee/CN=Timothee/emailAddress=timothee@unteem.org
```
It appears that the let's encrypt process succeeded, so I guess haproxy isn't picking up the cert.

Restarting haproxy picks up the cert.

```
core@libre / $ cd /system/haproxy && sudo libre restart
```

Known issue?

**Comment by edrex** [comment]
Realizing this may be "by design" and I should just be running `libre reload` on haproxy after adding a domain. Is this expected behavior?

**Comment by edrex** [comment]
https://cbonte.github.io/haproxy-dconv/1.7/management.html#4

**Comment by pierreozoux** [comment]
Strange, this shouldn't happen because of these lines:
https://github.com/indiehosters/docker-haproxy/blob/master/docker-entrypoint.sh#L10-L13

Is it the first cert or the following?

**Comment by pierreozoux** [comment]
I'll close this for now as it is old, but feel free to reopen if needed.
